// Gerado por scripts/generate-anp-catalog.mjs — não editar manualmente.
import type { OpenDataDataset } from "./openDataDataset";

export const ANP_CATALOG_DATASET_PATH = "anp/catalog/anp_catalog_compact.json";

export const ANP_OPEN_DATA_DATASETS: OpenDataDataset[] = [
  {
    id: "anp_tancagem_do_abastecimento_nacional_de_combustiveis",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "tancagem-do-abastecimento-nacional-de-combustiveis",
    title: "Tancagem do Abastecimento Nacional de Combustíveis",
    description: "A ANP propicia uma nova forma interativa de visualização de informações (a partir da ferramenta Power BI) no Painel Dinâmico sobre capacidade de tancagem (armazenamento) dos agentes regulados. São dados concretos, seguros e atualizados; capazes de subsidiar os tomadores de decisão em suas deliberações.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/tancagem-do-abastecimento-nacional-de-combustiveis",
  },
  {
    id: "anp_serie_historica_de_precos_de_combustiveis_e_de_glp",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "serie-historica-de-precos-de-combustiveis-e-de-glp",
    title: "Série Histórica de Preços de Combustíveis e de GLP",
    description: "Em cumprimento às determinações da Lei do Petróleo (Lei nº 9478/1997, artigo 8º), a ANP acompanha os preços praticados por revendedores de combustíveis automotivos e de gás liquefeito de petróleo envasilhado em botijões de 13 quilos (GLP P13), por meio de uma pesquisa semanal de preços realizada por empresa contratada. Veja abaixo os resultados das pesquisas que compõem a Série Histórica de Preços de Combustíveis (arquivos em formato .csv).",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/serie-historica-de-precos-de-combustiveis-e-de-glp",
  },
  {
    id: "anp_rodadas_de_licitacoes_de_petroleo_e_gas_natural",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "rodadas-de-licitacoes-de-petroleo-e-gas-natural",
    title: "Rodadas de Licitações de Petróleo e Gás Natural",
    description: "As Rodadas de Licitações são leilões por meio dos quais a União concede o direito de explorar e produzir petróleo e gás natural no Brasil. Mais informações sobre as rodadas podem ser obtidas no site das Rodadas da ANP. Apresentamos a lista de blocos ofertados e de ofertas vencedoras na 9ª a 15ª Rodada de Licitações de Blocos sob o regime de concessão, bem como o histórico de processos de Cessão de Contratos, de 2001 a 2017.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/rodadas-de-licitacoes-de-petroleo-e-gas-natural",
  },
  {
    id: "anp_resultado_de_poco",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "resultado-de-poco",
    title: "Resultado de poço",
    description: "O resultado de poço é o conjunto de atributos a partir dos quais podem simplificadamente se inferir conclusões gerais sobre as condições geológicas do prospecto perfurado por aquele poço, conforme Resolução ANP n° 699/2017.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/resultado-de-poco",
  },
  {
    id: "anp_relacao_de_concessionarios",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "relacao-de-concessionarios",
    title: "Relação de Concessionários",
    description: "Relação de Concessionários - A relação dos concessionários consolida informações dos contratos ativos na ANP. Estes contratos estão organizados por rodada de licitação. É possível visualizar a fase em que se encontra cada contrato, as empresas signatárias e suas respectivas participações. Relação de Concessionários - país de origem - Fazendo parte do conjunto, a relação dos concessionários consolida informações dos contratos ativos na ANP. Estes contratos estão organizados por rodada de licitação. É possível visualizar também os países de origem dos concessionários.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/relacao-de-concessionarios",
  },
  {
    id: "anp_registro_de_leos_e_graxas_lubrificantes",
    category_title: "Outros",
    subcategory_title: "Comércio e serviços",
    source_id: "anp",
    source_title: "ANP",
    slug: "registro-de-leos-e-graxas-lubrificantes",
    title: "Registro de Óleos e Graxas Lubrificantes",
    description: "A Resolução ANP n° 804/2019 estabelece os critérios para a obtenção do registro de graxas e óleos lubrificantes e as responsabilidades e obrigações dos detentores de registro, produtores e importadores. É por meio do registro de lubrificantes que a ANP obtém as especificações desses produtos, que variam conforme as aplicações existentes. Com as especificações, a Agência avalia a qualidade dos produtos no mercado, comparando os resultados de testes realizados em seu laboratório (CPT) com os valores das especificações de registro.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/registro-de-leos-e-graxas-lubrificantes",
  },
  {
    id: "anp_programa_de_monitoramento_dos_lubrificantes_pml",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Lubrificantes",
    source_id: "anp",
    source_title: "ANP",
    slug: "programa-de-monitoramento-dos-lubrificantes-pml",
    title: "Programa de Monitoramento dos Lubrificantes PML",
    description: "O Programa de Monitoramento dos Lubrificantes (PML) tem por objetivo acompanhar sistematicamente a qualidade dos óleos lubrificantes comercializados no país, bem como proporcionar uma ferramenta importante para o direcionamento das ações de fiscalização da ANP. O PML conta com laboratórios contratados pela ANP para coleta e envio das amostras para análise no Centro de Pesquisas e Análises Tecnológicas – CPT. A análise dos registros dos produtos, a execução dos ensaios físico-químicos e a avaliação dos resultados são realizados integralmente pelo CPT.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/programa-de-monitoramento-dos-lubrificantes-pml",
  },
  {
    id: "anp_producao_de_petroleo_e_gas_natural_por_estado_e_localizacao",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "producao-de-petroleo-e-gas-natural-por-estado-e-localizacao",
    title: "Produção de petróleo e gás natural por estado e localização",
    description: "As informações disponíveis são produção de petróleo; produção de LGN; produção de gás natural; reinjeção de gás natural; queima e perdas de gás natural; consumo próprio de gás natural; e gás natural disponível. Os dados são atualizados mensalmente até o último dia do mês subsequente ao mês de referência.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/producao-de-petroleo-e-gas-natural-por-estado-e-localizacao",
  },
  {
    id: "anp_producao_de_petroleo_e_gas_natural_por_poco",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "producao-de-petroleo-e-gas-natural-por-poco",
    title: "Produção de Petróleo e Gás Natural por Poço",
    description: "Os dados da produção mensal de petróleo e gás natural por poço têm sido publicados no site da ANP desde 2010, quando os primeiros dados foram divulgados junto com o histórico do quinquênio anterior (2005-2009).Além dos volumes de produção de petróleo (em bbl/dia) e gás natural (em Mm³/dia) em cada poço, também constam informações sobre localização (campo, bacia, estado), titularidade (operador, nº contrato), período de referência (mês e ano), grau API, fração de destilados, percentuais de hidrocarbonetos, dentre outras. Mensalmente são publicados três arquivos, com as listagens dos poços conforme a localização: terra, mar, pré-sal (neste último caso se trata dum subconjunto dos dados de produção em mar, contendo apenas os poços no polígono do pré-sal).Os dados não são divulgados no mês ime",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/producao-de-petroleo-e-gas-natural-por-poco",
  },
  {
    id: "anp_producao_de_biocombustiveis",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Biocombustíveis e renováveis",
    source_id: "anp",
    source_title: "ANP",
    slug: "producao-de-biocombustiveis",
    title: "Produção de Biocombustíveis",
    description: "As informações disponíveis no sítio da Agência Nacional do Petróleo, Gás Natural e Biocombustíveis são produção de biodiesel; e produção de etanol. Os dados são atualizados mensalmente até o último dia do mês subsequente ao mês de referência.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/producao-de-biocombustiveis",
  },
  {
    id: "anp_processamento_de_petroleo_e_producao_de_derivados",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "processamento-de-petroleo-e-producao-de-derivados",
    title: "Processamento de petróleo e produção de derivados",
    description: "As informações disponíveis são processamento de petróleo; produção de derivados por refinaria; produção de gás combustível por refinaria; produção de derivados por central petroquímica; produção de derivados de xisto; e produção de derivados por outros produtores. Os dados são atualizados mensalmente até o último dia do mês subsequente ao mês de referência.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/processamento-de-petroleo-e-producao-de-derivados",
  },
  {
    id: "anp_previso_de_investimentos_exploratrios",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "previso-de-investimentos-exploratrios",
    title: "Previsão de Investimentos Exploratórios",
    description: "Os contratos para exploração e produção, via de regra, são constituídos por duas fases: exploração e produção. A fase de exploração precede a fase de produção e tem por objetivo descobrir e avaliar jazidas de petróleo e/ou gás natural. O contrato estabelece um prazo durante o qual o concessionário ou contratado deve desenvolver atividades exploratórias de geologia e geofísica, visando ao maior conhecimento das bacias sedimentares brasileiras, em especial do bloco adquirido. As atividades exploratórias envolvem a aquisição de dados sísmicos, gravimétricos, magnetométricos, geoquímicos, perfuração e avaliação de poços, dentre outras, devendo obrigatoriamente contemplar o cumprimento do Programa Exploratório Mínimo (PEM) acordado com a ANP. Nessa consulta encontram-se os dados de quantidade d",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/previso-de-investimentos-exploratrios",
  },
  {
    id: "anp_prestadores_de_servicos_de_apoio_administrativo",
    category_title: "Outros",
    subcategory_title: "Administração",
    source_id: "anp",
    source_title: "ANP",
    slug: "prestadores-de-servicos-de-apoio-administrativo",
    title: "Prestadores de serviços de apoio administrativo",
    description: "Prestadores de serviços de apoio administrativo da ANP: Os dados disponibilizados trata-se da relação de prestadores de serviços terceirizados ocupantes dos postos de serviços objeto dos contratos de prestação de serviços de apoio administrativo no Escritório Central do Rio de Janeiro/RJ e do Escritório Sede em Brasília/DF.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/prestadores-de-servicos-de-apoio-administrativo",
  },
  {
    id: "anp_pontos_de_abastecimento_autorizados",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "pontos-de-abastecimento-autorizados",
    title: "Pontos de Abastecimento Autorizados",
    description: "Considerando que compete à ANP regular as atividades relativas ao abastecimento nacional de combustíveis, definido na Lei nº 9.847/1999, de 26 de outubro de 1999. A SDL (Superintendência de Distribuição e Logística) disponibiliza os metadados referentes aos Pontos de Abastecimento que estão em operação, conforme Resolução ANP nº 12/2007.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/pontos-de-abastecimento-autorizados",
  },
  {
    id: "anp_pesquisa_e_desenvolvimento_e_inovacao_pdi",
    category_title: "Outros",
    subcategory_title: "Pesquisa e desenvolvimento",
    source_id: "anp",
    source_title: "ANP",
    slug: "pesquisa-e-desenvolvimento-e-inovacao-pdi",
    title: "Pesquisa e Desenvolvimento e Inovação (PD&I)",
    description: "A Lei nº 9.478, de 06/08/1997, estabeleceu para a Agência Nacional do Petróleo, Gás Natural e Biocombustíveis (ANP), dentre outras, a atribuição de estimular a pesquisa e a adoção de novas tecnologias para o setor. Diante disso, os contratos celebrados entre a Agência e as Empresas Petrolíferas para exploração, desenvolvimento e produção de petróleo e gás natural dispõem, desde a Rodada Zero, de cláusulas de Pesquisa, Desenvolvimento e Inovação (Cláusula de PD&amp;I) que estabelecem a obrigação de realização de despesas qualificadas como PD&amp;I pelas Empresas Petrolíferas. A cláusula de PD&amp;I estabelece a aplicação de percentual da receita bruta da produção, segundo condições específicas de cada modalidade de contrato. A ANP é responsável pela análise, aprovação, acompanhamento e fisc",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/pesquisa-e-desenvolvimento-e-inovacao-pdi",
  },
];

