// Gerado por scripts/generate-anp-catalog.mjs — não editar manualmente.
import type { OpenDataDataset } from "./openDataDataset";

export const ANP_CATALOG_DATASET_PATH = "anp/catalog/anp_catalog_compact.json";

export const ANP_OPEN_DATA_DATASETS: OpenDataDataset[] = [
  {
    id: "anp_tancagem_do_abastecimento_nacional_de_combustiveis",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "tancagem-do-abastecimento-nacional-de-combustiveis",
    title: "Tancagem do Abastecimento Nacional de Combustíveis",
    description: "A ANP propicia uma nova forma interativa de visualização de informações (a partir da ferramenta Power BI) no Painel Dinâmico sobre capacidade de tancagem (armazenamento) dos agentes regulados. São dados concretos, seguros e atualizados; capazes de subsidiar os tomadores de decisão em suas deliberações.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/tancagem-do-abastecimento-nacional-de-combustiveis",
  },
  {
    id: "anp_serie_historica_de_precos_de_combustiveis_e_de_glp",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "serie-historica-de-precos-de-combustiveis-e-de-glp",
    title: "Série Histórica de Preços de Combustíveis e de GLP",
    description: "Em cumprimento às determinações da Lei do Petróleo (Lei nº 9478/1997, artigo 8º), a ANP acompanha os preços praticados por revendedores de combustíveis automotivos e de gás liquefeito de petróleo envasilhado em botijões de 13 quilos (GLP P13), por meio de uma pesquisa semanal de preços realizada por empresa contratada. Veja abaixo os resultados das pesquisas que compõem a Série Histórica de Preços de Combustíveis (arquivos em formato .csv).",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/serie-historica-de-precos-de-combustiveis-e-de-glp",
  },
  {
    id: "anp_rodadas_de_licitacoes_de_petroleo_e_gas_natural",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "rodadas-de-licitacoes-de-petroleo-e-gas-natural",
    title: "Rodadas de Licitações de Petróleo e Gás Natural",
    description: "As Rodadas de Licitações são leilões por meio dos quais a União concede o direito de explorar e produzir petróleo e gás natural no Brasil. Mais informações sobre as rodadas podem ser obtidas no site das Rodadas da ANP. Apresentamos a lista de blocos ofertados e de ofertas vencedoras na 9ª a 15ª Rodada de Licitações de Blocos sob o regime de concessão, bem como o histórico de processos de Cessão de Contratos, de 2001 a 2017.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/rodadas-de-licitacoes-de-petroleo-e-gas-natural",
  },
  {
    id: "anp_resultado_de_poco",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "resultado-de-poco",
    title: "Resultado de poço",
    description: "O resultado de poço é o conjunto de atributos a partir dos quais podem simplificadamente se inferir conclusões gerais sobre as condições geológicas do prospecto perfurado por aquele poço, conforme Resolução ANP n° 699/2017.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/resultado-de-poco",
  },
  {
    id: "anp_relacao_de_concessionarios",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "relacao-de-concessionarios",
    title: "Relação de Concessionários",
    description: "Relação de Concessionários - A relação dos concessionários consolida informações dos contratos ativos na ANP. Estes contratos estão organizados por rodada de licitação. É possível visualizar a fase em que se encontra cada contrato, as empresas signatárias e suas respectivas participações. Relação de Concessionários - país de origem - Fazendo parte do conjunto, a relação dos concessionários consolida informações dos contratos ativos na ANP. Estes contratos estão organizados por rodada de licitação. É possível visualizar também os países de origem dos concessionários.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/relacao-de-concessionarios",
  },
  {
    id: "anp_registro_de_leos_e_graxas_lubrificantes",
    category_title: "Outros",
    subcategory_title: "Comércio e serviços",
    source_id: "anp",
    source_title: "ANP",
    slug: "registro-de-leos-e-graxas-lubrificantes",
    title: "Registro de Óleos e Graxas Lubrificantes",
    description: "A Resolução ANP n° 804/2019 estabelece os critérios para a obtenção do registro de graxas e óleos lubrificantes e as responsabilidades e obrigações dos detentores de registro, produtores e importadores. É por meio do registro de lubrificantes que a ANP obtém as especificações desses produtos, que variam conforme as aplicações existentes. Com as especificações, a Agência avalia a qualidade dos produtos no mercado, comparando os resultados de testes realizados em seu laboratório (CPT) com os valores das especificações de registro.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/registro-de-leos-e-graxas-lubrificantes",
  },
  {
    id: "anp_programa_de_monitoramento_dos_lubrificantes_pml",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Lubrificantes",
    source_id: "anp",
    source_title: "ANP",
    slug: "programa-de-monitoramento-dos-lubrificantes-pml",
    title: "Programa de Monitoramento dos Lubrificantes PML",
    description: "O Programa de Monitoramento dos Lubrificantes (PML) tem por objetivo acompanhar sistematicamente a qualidade dos óleos lubrificantes comercializados no país, bem como proporcionar uma ferramenta importante para o direcionamento das ações de fiscalização da ANP. O PML conta com laboratórios contratados pela ANP para coleta e envio das amostras para análise no Centro de Pesquisas e Análises Tecnológicas – CPT. A análise dos registros dos produtos, a execução dos ensaios físico-químicos e a avaliação dos resultados são realizados integralmente pelo CPT.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/programa-de-monitoramento-dos-lubrificantes-pml",
  },
  {
    id: "anp_producao_de_petroleo_e_gas_natural_por_estado_e_localizacao",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "producao-de-petroleo-e-gas-natural-por-estado-e-localizacao",
    title: "Produção de petróleo e gás natural por estado e localização",
    description: "As informações disponíveis são produção de petróleo; produção de LGN; produção de gás natural; reinjeção de gás natural; queima e perdas de gás natural; consumo próprio de gás natural; e gás natural disponível. Os dados são atualizados mensalmente até o último dia do mês subsequente ao mês de referência.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/producao-de-petroleo-e-gas-natural-por-estado-e-localizacao",
  },
  {
    id: "anp_producao_de_petroleo_e_gas_natural_por_poco",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "producao-de-petroleo-e-gas-natural-por-poco",
    title: "Produção de Petróleo e Gás Natural por Poço",
    description: "Os dados da produção mensal de petróleo e gás natural por poço têm sido publicados no site da ANP desde 2010, quando os primeiros dados foram divulgados junto com o histórico do quinquênio anterior (2005-2009).Além dos volumes de produção de petróleo (em bbl/dia) e gás natural (em Mm³/dia) em cada poço, também constam informações sobre localização (campo, bacia, estado), titularidade (operador, nº contrato), período de referência (mês e ano), grau API, fração de destilados, percentuais de hidrocarbonetos, dentre outras. Mensalmente são publicados três arquivos, com as listagens dos poços conforme a localização: terra, mar, pré-sal (neste último caso se trata dum subconjunto dos dados de produção em mar, contendo apenas os poços no polígono do pré-sal).Os dados não são divulgados no mês ime",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/producao-de-petroleo-e-gas-natural-por-poco",
  },
  {
    id: "anp_producao_de_biocombustiveis",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Biocombustíveis e renováveis",
    source_id: "anp",
    source_title: "ANP",
    slug: "producao-de-biocombustiveis",
    title: "Produção de Biocombustíveis",
    description: "As informações disponíveis no sítio da Agência Nacional do Petróleo, Gás Natural e Biocombustíveis são produção de biodiesel; e produção de etanol. Os dados são atualizados mensalmente até o último dia do mês subsequente ao mês de referência.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/producao-de-biocombustiveis",
  },
  {
    id: "anp_processamento_de_petroleo_e_producao_de_derivados",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "processamento-de-petroleo-e-producao-de-derivados",
    title: "Processamento de petróleo e produção de derivados",
    description: "As informações disponíveis são processamento de petróleo; produção de derivados por refinaria; produção de gás combustível por refinaria; produção de derivados por central petroquímica; produção de derivados de xisto; e produção de derivados por outros produtores. Os dados são atualizados mensalmente até o último dia do mês subsequente ao mês de referência.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/processamento-de-petroleo-e-producao-de-derivados",
  },
  {
    id: "anp_previso_de_investimentos_exploratrios",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "previso-de-investimentos-exploratrios",
    title: "Previsão de Investimentos Exploratórios",
    description: "Os contratos para exploração e produção, via de regra, são constituídos por duas fases: exploração e produção. A fase de exploração precede a fase de produção e tem por objetivo descobrir e avaliar jazidas de petróleo e/ou gás natural. O contrato estabelece um prazo durante o qual o concessionário ou contratado deve desenvolver atividades exploratórias de geologia e geofísica, visando ao maior conhecimento das bacias sedimentares brasileiras, em especial do bloco adquirido. As atividades exploratórias envolvem a aquisição de dados sísmicos, gravimétricos, magnetométricos, geoquímicos, perfuração e avaliação de poços, dentre outras, devendo obrigatoriamente contemplar o cumprimento do Programa Exploratório Mínimo (PEM) acordado com a ANP. Nessa consulta encontram-se os dados de quantidade d",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/previso-de-investimentos-exploratrios",
  },
  {
    id: "anp_prestadores_de_servicos_de_apoio_administrativo",
    category_title: "Outros",
    subcategory_title: "Administração",
    source_id: "anp",
    source_title: "ANP",
    slug: "prestadores-de-servicos-de-apoio-administrativo",
    title: "Prestadores de serviços de apoio administrativo",
    description: "Prestadores de serviços de apoio administrativo da ANP: Os dados disponibilizados trata-se da relação de prestadores de serviços terceirizados ocupantes dos postos de serviços objeto dos contratos de prestação de serviços de apoio administrativo no Escritório Central do Rio de Janeiro/RJ e do Escritório Sede em Brasília/DF.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/prestadores-de-servicos-de-apoio-administrativo",
  },
  {
    id: "anp_pontos_de_abastecimento_autorizados",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "pontos-de-abastecimento-autorizados",
    title: "Pontos de Abastecimento Autorizados",
    description: "Considerando que compete à ANP regular as atividades relativas ao abastecimento nacional de combustíveis, definido na Lei nº 9.847/1999, de 26 de outubro de 1999. A SDL (Superintendência de Distribuição e Logística) disponibiliza os metadados referentes aos Pontos de Abastecimento que estão em operação, conforme Resolução ANP nº 12/2007.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/pontos-de-abastecimento-autorizados",
  },
  {
    id: "anp_pesquisa_e_desenvolvimento_e_inovacao_pdi",
    category_title: "Outros",
    subcategory_title: "Pesquisa e desenvolvimento",
    source_id: "anp",
    source_title: "ANP",
    slug: "pesquisa-e-desenvolvimento-e-inovacao-pdi",
    title: "Pesquisa e Desenvolvimento e Inovação (PD&I)",
    description: "A Lei nº 9.478, de 06/08/1997, estabeleceu para a Agência Nacional do Petróleo, Gás Natural e Biocombustíveis (ANP), dentre outras, a atribuição de estimular a pesquisa e a adoção de novas tecnologias para o setor. Diante disso, os contratos celebrados entre a Agência e as Empresas Petrolíferas para exploração, desenvolvimento e produção de petróleo e gás natural dispõem, desde a Rodada Zero, de cláusulas de Pesquisa, Desenvolvimento e Inovação (Cláusula de PD&amp;I) que estabelecem a obrigação de realização de despesas qualificadas como PD&amp;I pelas Empresas Petrolíferas. A cláusula de PD&amp;I estabelece a aplicação de percentual da receita bruta da produção, segundo condições específicas de cada modalidade de contrato. A ANP é responsável pela análise, aprovação, acompanhamento e fisc",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/pesquisa-e-desenvolvimento-e-inovacao-pdi",
  },
  {
    id: "anp_participacoes_governamentais",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "participacoes-governamentais",
    title: "Participações Governamentais",
    description: "Dados consolidados pela Agência Nacional do Petróleo, Gás Natural e Biocombustíveis/ANP sobre as unidades de pesquisa credenciadas para a execução de projetos com recursos provenientes da cláusula de PD&",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/participacoes-governamentais",
  },
  {
    id: "anp_paineis_de_producao_de_etanol_e_de_biodiesel",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Biocombustíveis e renováveis",
    source_id: "anp",
    source_title: "ANP",
    slug: "paineis-de-producao-de-etanol-e-de-biodiesel",
    title: "Painéis de Produção de Etanol e de Biodiesel",
    description: "A ANP propicia uma nova forma interativa de visualização dos dados de produção de etanol e biodiesel oriundos das declarações dos agentes via Sistema de Informações de Movimentação de Produtos (Simp). Informações temporais relativas à produção regional, matéria-prima e tancagem de etanol e biodiesel podem ser obtidas a partir dos dados disponibilizados nesta página ou nos painéis dinâmicos do site da ANP.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/paineis-de-producao-de-etanol-e-de-biodiesel",
  },
  {
    id: "anp_painel_de_produtores_de_derivados_vendas_de_derivados_de_petroleo_e_biocombustiveis",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Biocombustíveis e renováveis",
    source_id: "anp",
    source_title: "ANP",
    slug: "painel-de-produtores-de-derivados-vendas-de-derivados-de-petroleo-e-biocombustiveis",
    title: "Painel de Produtores de Derivados: Vendas de derivados de petróleo e biocombustíveis",
    description: "São apresentados os dados referentes à quantidade de biodiesel vendido entre a UF de origem e a UF de destino informados pelos produtores de biodiesel cadastrados na Agência Nacional do Petróleo, Gás Natural e Biocombustíveis/ANP.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/painel-de-produtores-de-derivados-vendas-de-derivados-de-petroleo-e-biocombustiveis",
  },
  {
    id: "anp_painel_dinamico_de_processamento_de_petroleo_e_producao_de_derivados",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "painel-dinamico-de-processamento-de-petroleo-e-producao-de-derivados",
    title: "Painel Dinâmico de Processamento de petróleo e produção de derivados",
    description: "A ANP propicia uma nova forma interativa de visualização dos dados de produção de combustíveis e derivados de petróleo oriundos das declarações dos agentes via Sistema de Informações de Movimentação de Produtos (Simp). Informações temporais relativas ao processamento de petróleo e fator de utilização efetiva, participação das refinarias no processamento de petróleo, produção e operações de derivados nas refinarias, bem como produção de combustíveis em centrais petroquímicas e formuladores podem ser obtidas a partir do uso dessa ferramenta.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/painel-dinamico-de-processamento-de-petroleo-e-producao-de-derivados",
  },
  {
    id: "anp_pmqc___programa_de_monitoramento_da_qualidade_dos_combustiveis",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "pmqc---programa-de-monitoramento-da-qualidade-dos-combustiveis",
    title: "PMQC - Programa de Monitoramento da Qualidade dos Combustíveis",
    description: "Levantamento dos indicadores gerais da qualidade dos combustíveis comercializados no País e a identificação de focos de não conformidade, visando à simetria de informações e a orientar e aperfeiçoar a atuação da área de fiscalização. Os dados desta página encontram-se exclusivamente em formato CSV, caso deseje o formato JSON sugerimos que visite a página Programa de Monitoramento da Qualidade dos Combustíveis (PMQC) no site https://www.gov.br/anp/pt-br/centrais-de-conteudo/dados-abertos/pmqc-programa-de-monitoramento-da-qualidade-dos-combustiveis.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/pmqc---programa-de-monitoramento-da-qualidade-dos-combustiveis",
  },
  {
    id: "anp_multas_aplicadas___vencimento_a_partir_de_2016",
    category_title: "Outros",
    subcategory_title: "Administração",
    source_id: "anp",
    source_title: "ANP",
    slug: "multas-aplicadas---vencimento-a-partir-de-2016",
    title: "Multas aplicadas - vencimento a partir de 2016",
    description: "A ANP disponibiliza abaixo a relação de multas aplicadas com vencimento a partir de 2016. Cabe ressaltar que a ANP apenas aplica as multas e que toda a receita delas decorrente é recolhida diretamente ao Tesouro Nacional. O agente econômico autuado pela ANP tem assegurado o direito à ampla defesa e ao contraditório em todo trâmite processual.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/multas-aplicadas---vencimento-a-partir-de-2016",
  },
  {
    id: "anp_movimentacao_dos_terminais_aquaviarios",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "movimentacao-dos-terminais-aquaviarios",
    title: "Movimentação dos Terminais Aquaviários",
    description: "A Resolução ANP nº 881/2022 estabelece critérios para o uso dos terminais aquaviários existentes, ou a serem construídos, para movimentação de petróleo, de derivados de petróleo, de derivados de gás natural e de biocombustíveis. Dentre as obrigações do operador de terminal aquaviário está a publicação mensal, em seu site, de dados sobre a movimentação de produtos regulados pela ANP em sua instalação, conforme modelo definido pela ANP. A ANP compila mensalmente esses dados e os publica no formato de dados abertos e no Painel Dinâmico de Aplicação da Resolução ANP nº 881/2022. O painel disponibiliza diversos dados públicos sobre os terminais aquaviários autorizados a operar pela ANP. A série histórica inicia em 2022-09, primeiro de referência com obrigação de publicidade no formato padroniza",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/movimentacao-dos-terminais-aquaviarios",
  },
  {
    id: "anp_movimentacao_de_derivados_de_petroleo_e_biocombustiveis",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Biocombustíveis e renováveis",
    source_id: "anp",
    source_title: "ANP",
    slug: "movimentacao-de-derivados-de-petroleo-e-biocombustiveis",
    title: "Movimentação de derivados de petróleo e biocombustíveis",
    description: "Asfaltos - Divulga a movimentação de asfaltos pelos agentes regulados, conforme Resolução ANP nº 729/2018, com a garantia da proteção das informações declaradas pelos agentes, conforme previsto no art. 3º da referida Resolução. Combustíveis de aviação - Divulga a movimentação de combustíveis de aviação (Gasolina e querosene de aviação) pelos agentes regulados, conforme Resolução ANP nº 729/2018, com a garantia da proteção das informações declaradas pelos agentes, conforme previsto no art. 3º da referida Resolução. Combustíveis líquidos - Divulga a movimentação de combustíveis líquidos (exceto combustíveis de aviação) pelos agentes regulados, conforme Resolução ANP nº 729/2018, com a garantia da proteção das informações declaradas pelos agentes, conforme previsto no art. 3º da referida Reso",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/movimentacao-de-derivados-de-petroleo-e-biocombustiveis",
  },
  {
    id: "anp_importacoes_e_exportacoes",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "importacoes-e-exportacoes",
    title: "Importações e exportações",
    description: "As informações disponíveis são importações exportações de petróleo; importações de gás natural; importações e exportações de derivados petróleo; e importações e exportações de etanol. Os dados são atualizados mensalmente até o último dia do mês subsequente ao mês de referência.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/importacoes-e-exportacoes",
  },
  {
    id: "anp_gestao_de_contratos_de_exploracao_e_producao__dados_de_ep",
    category_title: "Outros",
    subcategory_title: "Administração",
    source_id: "anp",
    source_title: "ANP",
    slug: "gestao-de-contratos-de-exploracao-e-producao--dados-de-ep",
    title: "Gestão de Contratos de Exploração e Produção – Dados de E&P",
    description: "Os contratos para exploração e produção, via de regra, são constituídos por duas fases: exploração e produção. A fase de exploração precede a fase de produção e tem por objetivo descobrir e avaliar jazidas de petróleo e/ou gás natural. O contrato estabelece um prazo, usualmente dividido em períodos exploratórios, durante o qual o concessionário ou contratado deve desenvolver atividades exploratórias de geologia e geofísica, visando ao maior conhecimento das bacias sedimentares brasileiras, em especial do bloco adquirido. As atividades exploratórias envolvem a aquisição de dados sísmicos, gravimétricos, magnetométricos, geoquímicos, perfuração e avaliação de poços, dentre outras, devendo obrigatoriamente contemplar o cumprimento do Programa Exploratório Mínimo (PEM) acordado com a ANP. Tamb",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/gestao-de-contratos-de-exploracao-e-producao--dados-de-ep",
  },
  {
    id: "anp_fiscalizacao_de_conteudo_local",
    category_title: "Outros",
    subcategory_title: "Administração",
    source_id: "anp",
    source_title: "ANP",
    slug: "fiscalizacao-de-conteudo-local",
    title: "Fiscalização de Conteúdo Local",
    description: "Controle dos processos de fiscalização do cumprimento das obrigações de conteúdo local dos contratos de E&amp A ANP é responsável por fiscalizar o cumprimento dos percentuais de Conteúdo Local (CL) definidos nos contratos de exploração e produção de petróleo e gás natural, sob os regimes de concessão, cessão onerosa e de partilha da produção. Os percentuais de Conteúdo Local são definidos pelo Conselho Nacional de Política Energética (CNPE), por ocasião das rodadas de licitações realizadas pela ANP, e correspondem à proporção entre o somatório de valor dos bens e serviços nacionais para as operações de exploração e desenvolvimento da produção de petróleo a gás natural e o valor total dispendido para esta finalidade, calculado ao término da fase de exploração e da etapa de desenvolvimento d",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/fiscalizacao-de-conteudo-local",
  },
  {
    id: "anp_fase_de_exploracao",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "fase-de-exploracao",
    title: "Fase de Exploração",
    description: "Painel Dinâmico da Fase de Exploração Informações sobre os Blocos sob Contrato; Poços Exploratórios; Planos de Avaliação de Descobertas em Andamento; Planos de Avaliação de Descobertas Concluídos – PADs concluídos, apresentando, dentre outras informações, o ano de término efetivo dos planos; e Declarações de Comercialidade. Prorrogação de Prazos da Fase de Exploração Informações sobre os contratos de exploração e produção de petróleo e gás natural (E&P) na fase de exploração para os quais houve prorrogação mediante as Resoluções abaixo: Processos Sancionadores Dados gerais referente à situação dos processos sancionadores de exploração de petróleo e gás natural",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/fase-de-exploracao",
  },
  {
    id: "anp_fase_de_desenvolvimento_e_producao",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "fase-de-desenvolvimento-e-producao",
    title: "Fase de Desenvolvimento e Produção",
    description: "A Fase de Produção é o período contratual em que devem ocorrer o Desenvolvimento e a Produção. A fase de produção de cada área de desenvolvimento terá início na data da apresentação da Declaração de Comercialidade (DC) e duração a depender do regime do contrato.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/fase-de-desenvolvimento-e-producao",
  },
  {
    id: "anp_distribuidores_de_combustiveis_liquidos",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "distribuidores-de-combustiveis-liquidos",
    title: "Distribuidores de Combustíveis Líquidos",
    description: "Considerando que compete à ANP regular as atividades relativas ao abastecimento nacional de combustíveis, definido na Lei nº 9.847/1999, de 26 de outubro de 1999. A SDL (Superintendência de Distribuição e Logística) disponibiliza os metadados abaixo, a saber: Empresa inutilizadora de botijão de GLP: empresa cadastrada para execução do serviço de inutilização de botijões, nos termos da Norma Técnica NBR 8866, da ABNT; Cessão de Espaço: Contrato homologado entre a cedente (base de combustíveis ou liquefeitos, refinaria, terminal ou produtora de etanol) e cessionária (distribuidor de combustíveis líquidos, aviação, GLP ou TRR), ajustando o uso temporário de espaço de tancagem cedido; Carregamento Rodoviário: Contrato identificando o ponto de entrega direta de combustíveis líquidos automotivos",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/distribuidores-de-combustiveis-liquidos",
  },
  {
    id: "anp_dados_de_incidentes_de_exploracao_e_producao_de_petroleo_e_gas_natural",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "dados-de-incidentes-de-exploracao-e-producao-de-petroleo-e-gas-natural",
    title: "Dados de Incidentes de Exploração e Produção de Petróleo e Gás Natural",
    description: "Nessa seção são divulgados os dados de incidentes ocorridos nas atividades de Exploração e Produção. De acordo com os procedimentos estabelecidos na Resolução ANP nº 882/2022, a ANP recebe a Comunicação Inicial (CI) relativa aos incidentes por meio do Sistema Integrado de Segurança Operacional, módulo de Incidentes (SISO-Incidentes). As comunicações são realizadas de acordo com o Manual de Comunicação de Incidentes e suas informações integram uma base de dados de incidentes nas atividades de E&P. Os dados são divulgados nos termos da Lei nº 12.527 de 18 de novembro de 2011 (“Lei de Acesso à Informação – LAI”) e do decreto que a regulamentou (Decreto nº 7.724/2012), garantindo a aplicação do disposto no art. 5º, § 2º e do Art. 55 do Decreto nº 7.724/2012. Ou seja: sua divulgação não configu",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/dados-de-incidentes-de-exploracao-e-producao-de-petroleo-e-gas-natural",
  },
  {
    id: "anp_dados_georreferenciados_das_bacias_sedimentares_brasileiras",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "dados-georreferenciados-das-bacias-sedimentares-brasileiras",
    title: "Dados Georreferenciados das Bacias Sedimentares Brasileiras",
    description: "O GeoANP é uma ferramenta interativa que reúne informações do segmento de exploração e produção, exibidos num mapa interativo de dados georreferenciados (geoespaciais). Estão disponíveis informações relacionadas aos dados técnicos e levantamentos das bacias sedimentares brasileiras, como por exemplo poços perfurados, dados sísmicos e blocos licitados nas rodadas. É possível a exportação dessas informações por meio de arquivos shapefile. O shapefile é um formato aberto de arquivo contendo dados geoespaciais em forma vetorial, representando pontos, linhas e polígonos; usado por Sistemas de Informações Geográficas (SIG). Alguns dos shapefiles obtidos no GeoANP também são disponibilizados diretamente no site da ANP, para agilizar o acesso pelos entes externos. Esses shapefiles podem ser baixad",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/dados-georreferenciados-das-bacias-sedimentares-brasileiras",
  },
  {
    id: "anp_dados_consolidados_de_movimentacao_de_gas_natural_em_gasodutos_de_transporte",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "dados-consolidados-de-movimentacao-de-gas-natural-em-gasodutos-de-transporte",
    title: "Dados Consolidados de Movimentação de Gás Natural em Gasodutos de Transporte",
    description: "O conjunto dos dados abertos de movimentação de gás natural em gasodutos de transporte enviados pelos Transportadores, com previsão de publicação e disseminação na Web estabelecida no § 2º, Art. 1º, da Resolução ANP nº 40, de 09/09/2016.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/dados-consolidados-de-movimentacao-de-gas-natural-em-gasodutos-de-transporte",
  },
  {
    id: "anp_dados_cadastrais_dos_revendedores_varejistas_de_combustiveis_automotivos",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Abastecimento e mercado",
    source_id: "anp",
    source_title: "ANP",
    slug: "dados-cadastrais-dos-revendedores-varejistas-de-combustiveis-automotivos",
    title: "Dados Cadastrais dos Revendedores Varejistas de Combustíveis Automotivos",
    description: "Considerando que compete à ANP regular as atividades relativas ao abastecimento nacional de combustíveis, definido na Lei nº 9.847/1999, de 26 de outubro de 1999. A SDL (Superintendência de Distribuição e Logística) disponibiliza os metadados referentes aos revendedores varejistas de combustíveis automotivos que estão em operação.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/dados-cadastrais-dos-revendedores-varejistas-de-combustiveis-automotivos",
  },
  {
    id: "anp_dados_cadastrais_das_revendas_de_gas_liquefeito_de_petroleo_glp",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "dados-cadastrais-das-revendas-de-gas-liquefeito-de-petroleo-glp",
    title: "Dados Cadastrais das Revendas de Gás Liquefeito de Petróleo (GLP)",
    description: "Considerando que compete à ANP regular as atividades relativas ao abastecimento nacional de combustíveis, definido na Lei nº 9.847/1999, de 26 de outubro de 1999. A SDL (Superintendência de Distribuição e Logística) disponibiliza os metadados referentes aos revendedores de gás liquefeito de petróleo (GLP).",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/dados-cadastrais-das-revendas-de-gas-liquefeito-de-petroleo-glp",
  },
  {
    id: "anp_comercializacao_de_gas_natural",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "comercializacao-de-gas-natural",
    title: "Comercialização de Gás Natural",
    description: "O conjunto dos dados abertos de comercialização de gás natural são constituídos de 2 arquivos: Vendas às distribuidoras ou consumidores livres: São as vendas de gás natural para as companhias locais de distribuição de gás natural ou consumidores livres que tenham autorização dos estados para comprar diretamente o gás natural dos agentes vendedores. Os dados contém as informações de preços médios ponderados pelos volumes comercializados, bem como os próprios volumes comercializados, e são divulgados mensalmente. Os dados são agregados por regiões brasileiras de acordo com a necessidade de preservação do sigilo comercial dos agentes. Vendas entre produtores: São as vendas de gás natural entre produtores de gás natural. Os dados contém as informações de preços médios ponderados pelos volumes ",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/comercializacao-de-gas-natural",
  },
  {
    id: "anp_capacidade_de_armazenagem_de_terminais",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "capacidade-de-armazenagem-de-terminais",
    title: "Capacidade de Armazenagem de Terminais",
    description: "Os terminais são instalações voltadas à logística de movimentação e armazenamento dos produtos líquidos regulados pela ANP: petróleo, seus derivados e biocombustíveis. Essas instalações compõem a infraestrutura nacional de transporte e transferência desses produtos e são compostas por tanques, bombas, linhas e todos os equipamentos necessários para carga e descarga, visando principalmente a alteração de modo de transporte ou alteração do tamanho do lote de produto. Seu objetivo, na maioria dos casos, é prestar o serviço de movimentação e armazenagem para outras empresas que compõem a indústria do petróleo e dos biocombustíveis. A operação e a construção de terminais para movimentação de petróleo, seus derivados, gás natural, inclusive liquefeito (GNL), biocombustíveis e demais produtos reg",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/capacidade-de-armazenagem-de-terminais",
  },
  {
    id: "anp_blocos_com_fase_exploratoria_encerrada",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "blocos-com-fase-exploratoria-encerrada",
    title: "Blocos com Fase Exploratória Encerrada",
    description: "Blocos com fase exploratória encerrada",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/blocos-com-fase-exploratoria-encerrada",
  },
  {
    id: "anp_acoes_de_fiscalizacao_do_abastecimento",
    category_title: "Outros",
    subcategory_title: "Administração",
    source_id: "anp",
    source_title: "ANP",
    slug: "acoes-de-fiscalizacao-do-abastecimento",
    title: "Ações de Fiscalização do Abastecimento",
    description: "Compete à Superintendência de Fiscalização do Abastecimento (SFI), com apoio dos Núcleos Regionais de Fiscalização, planejar e executar as ações de fiscalização dos agentes que compõem o abastecimento nacional de combustíveis em todo o território nacional. Com base nessa competência e com o intuito de dar maior transparência às suas ações, a SFI disponibiliza os resultados das ações de fiscalização do abastecimento. Tais dados serão atualizados mensalmente, com prazo de dois meses entre o mês da fiscalização e o mês da publicação, devido ao atendimento de exigências legais e aspectos operacionais. Os agentes econômicos autuados possuem direito ao contraditório e à ampla defesa assegurado pela lei. Dessa forma, somente após o julgamento definitivo do processo administrativo sancionador, ger",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/acoes-de-fiscalizacao-do-abastecimento",
  },
  {
    id: "anp_autorizacoes_de_gas_natural",
    category_title: "Outros",
    subcategory_title: "Administração",
    source_id: "anp",
    source_title: "ANP",
    slug: "autorizacoes-de-gas-natural",
    title: "Autorizações de gás natural",
    description: "As autorizações para Instalações de Transporte e/ou Movimentação de gás natural na ANP são regidas pelas seguintes regulamentações: - Portaria Nº 118 de 11 de julho de 2000 para as atividades de distribuição de gás natural liquefeito (GNL) a granel e de construção, ampliação e operação das centrais de distribuição de GNL; - Resolução ANP 41 de 05 de dezembro de 2007 para a atividade de Distribuição de Gás Natural Comprimido (GNC) a Granel, a realização de Projeto para Uso Próprio e de Projeto Estruturante; - Resolução ANP 52 de 02 de dezembro de 2015 para a construção, a ampliação e a operação de instalações de movimentação de produtos regulados pela ANP, onde está incluso o gás natural, inclusive liquefeito (GNL). A RANP 52/2015 abrange além de dutos e terminais, os sistemas indispensávei",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/autorizacoes-de-gas-natural",
  },
  {
    id: "anp_aquisicao_processamento_e_estudo_de_dados",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "aquisicao-processamento-e-estudo-de-dados",
    title: "Aquisição, Processamento e Estudo de Dados",
    description: "As atividades de aquisição, processamento e estudo de dados não exclusivos (adquiridos por Empresas de Aquisição de Dados - EADs) e de fomento (adquiridos por universidades, instituições de pesquisa ou empresas contratadas pela ANP) somente podem ser realizadas mediante autorização prévia da ANP, conforme a Resolução ANP nº 757/2018. Já o que for relacionado a dados exclusivos (adquiridos pelas concessionárias / operadoras) está dispensado de autorização. Atualmente, as autorizações outorgadas pela ANP têm vigência de cinco anos, não prorrogáveis, contados a partir da data de sua publicação no Diário Oficial da União. Anteriormente à Resolução ANP nº 757/2018 não havia prazo fixo ou restrição a prorrogações. Caso fosse consentida a prorrogação de uma autorização vigente, era publicado no D",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/aquisicao-processamento-e-estudo-de-dados",
  },
  {
    id: "anp_anurio_estatstico_2025",
    category_title: "Outros",
    subcategory_title: "Administração",
    source_id: "anp",
    source_title: "ANP",
    slug: "anurio-estatstico-2025",
    title: "Anuário Estatístico 2025",
    description: "O Anuário Estatístico Brasileiro do Petróleo, Gás Natural e Biocombustíveis 2025 consolida os dados referentes ao desempenho da indústria do petróleo, gás natural e biocombustíveis e do sistema de abastecimento nacionais no período 2015-2024. Estão disponíveis para consulta e download as tabelas integrantes do Anuário 2025 representadas em metadados e no formato CSV.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/anurio-estatstico-2025",
  },
  {
    id: "anp_anuario_estatistico_2024",
    category_title: "Outros",
    subcategory_title: "Pesquisa e desenvolvimento",
    source_id: "anp",
    source_title: "ANP",
    slug: "anuario-estatistico-2024",
    title: "Anuário Estatístico 2024",
    description: "O Anuário Estatístico Brasileiro do Petróleo, Gás Natural e Biocombustíveis 2024 consolida os dados referentes ao desempenho da indústria do petróleo, gás natural e biocombustíveis e do sistema de abastecimento nacionais no período 2014-2023. Estão disponíveis para consulta e download as tabelas integrantes do Anuário 2024 representadas em metadados e no formato CSV.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/anuario-estatistico-2024",
  },
  {
    id: "anp_anuario_estatistico_2023",
    category_title: "Outros",
    subcategory_title: "Pesquisa e desenvolvimento",
    source_id: "anp",
    source_title: "ANP",
    slug: "anuario-estatistico-2023",
    title: "Anuário Estatístico 2023",
    description: "O Anuário Estatístico Brasileiro do Petróleo, Gás Natural e Biocombustíveis 2023 consolida os dados referentes ao desempenho da indústria do petróleo, gás natural e biocombustíveis e do sistema de abastecimento nacionais no período 2013-2022. Estão disponíveis para consulta e download as tabelas integrantes do Anuário 2023 representadas em metadados e no formato CSV. A ANP não divulgará os dados de reservas internacionais provadas de petróleo e gás natural de 2021 e 2022, porque o Statistical Review of World Energy 2023, nossa fonte de dados internacionais, não publicou esses dados. Portanto serão repetidos os dados do Anuário de 2022.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/anuario-estatistico-2023",
  },
  {
    id: "anp_anuario_estatistico_2022",
    category_title: "Outros",
    subcategory_title: "Pesquisa e desenvolvimento",
    source_id: "anp",
    source_title: "ANP",
    slug: "anuario-estatistico-2022",
    title: "Anuário Estatístico 2022",
    description: "O Anuário Estatístico Brasileiro do Petróleo, Gás Natural e Biocombustíveis 2022 consolida os dados referentes ao desempenho da indústria do petróleo, gás natural e biocombustíveis e do sistema de abastecimento nacionais no período 2012-2021. Estão disponíveis para consulta e download as tabelas integrantes do Anuário 2022 representadas em metadados e no formato CSV. A ANP não divulgará os dados de reservas internacionais provadas de petróleo e gás natural de 2021, porque o BP Statistical Review of World Energy 2022, nossa fonte de dados internacionais, ainda não publicou esses dados. Portanto serão repetidos os dados do Anuário de 2021.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/anuario-estatistico-2022",
  },
  {
    id: "anp_anurio_estatstico_2021",
    category_title: "Outros",
    subcategory_title: "Pesquisa e desenvolvimento",
    source_id: "anp",
    source_title: "ANP",
    slug: "anurio-estatstico-2021",
    title: "Anuário Estatístico 2021",
    description: "<p>O Anuário Estatístico Brasileiro do Petróleo, Gás Natural e Biocombustíveis 2021 consolida os dados referentes ao desempenho da indústria do petróleo, gás natural e biocombustíveis e do sistema de abastecimento nacionais no período 2011-2020. Estão disponíveis para consulta e download as tabelas integrantes do Anuário 2021 representadas em formato de dados abertos.</p>",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/anurio-estatstico-2021",
  },
  {
    id: "anp_anuario_estatistico_2020",
    category_title: "Outros",
    subcategory_title: "Pesquisa e desenvolvimento",
    source_id: "anp",
    source_title: "ANP",
    slug: "anuario-estatistico-2020",
    title: "Anuário Estatístico 2020",
    description: "O Anuário Estatístico Brasileiro do Petróleo, Gás Natural e Biocombustíveis 2020 consolida os dados referentes ao desempenho da indústria do petróleo, gás natural e biocombustíveis e do sistema de abastecimento nacionais no período 2010-2019. Estão disponíveis para consulta e download as tabelas integrantes do Anuário 2020 representadas em formato de dados abertos.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/anuario-estatistico-2020",
  },
  {
    id: "anp_anurio_estatstico_2019",
    category_title: "Outros",
    subcategory_title: "Pesquisa e desenvolvimento",
    source_id: "anp",
    source_title: "ANP",
    slug: "anurio-estatstico-2019",
    title: "Anuário Estatístico 2019",
    description: "<p>O Anuário Estatístico Brasileiro do Petróleo, Gás Natural e Biocombustíveis 2019 consolida os dados referentes ao desempenho da indústria do petróleo, gás natural e biocombustíveis e do sistema de abastecimento nacionais no período 2009-2018. Estão disponíveis para consulta e download as tabelas integrantes do Anuário 2019 representadas em formato de dados abertos.</p>",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/anurio-estatstico-2019",
  },
  {
    id: "anp_anuario_estatistico_2018",
    category_title: "Outros",
    subcategory_title: "Pesquisa e desenvolvimento",
    source_id: "anp",
    source_title: "ANP",
    slug: "anuario-estatistico-2018",
    title: "Anuário Estatístico 2018",
    description: "O Anuário Estatístico Brasileiro de Petróleo, Gás Natural e Biocombustíveis 2018 consolida os dados referentes ao desempenho da indústria e do sistema de abastecimento de petróleo, gás natural e biocombustíveis no período de 2008 a 2017.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/anuario-estatistico-2018",
  },
  {
    id: "anp_amostras_de_rochas_e_fluidos",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "amostras-de-rochas-e-fluidos",
    title: "Amostras de Rochas e Fluidos",
    description: "Amostras são porção de rocha, sedimento ou fluido extraído de poço, da superfície do fundo oceânico ou da superfície terrestre. Os procedimentos para coleta e manejo das amostras nas bacias sedimentares brasileiras estão definidos na Resolução ANP n° 71/2014. Eis alguns dos tipos de amostras coletadas: testemunhos de sondagem e seus respectivos plugues; amostras de calha; amostras laterais; amostras de fluidos; lâminas delgadas, bioestratigráficas e seções polidas. Considerando que a ANP ainda não possui uma estrutura definitiva para o recebimento dessas amostras , as empresas responsáveis pela aquisição são suas fiéis depositárias. A ANP realiza o controle dessas amostras por meio de ações de fiscalização e controle documental e de campo, e assegura a aplicação das regras estipuladas para",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/amostras-de-rochas-e-fluidos",
  },
  {
    id: "anp_aditamento_de_conteudo_local",
    category_title: "Outros",
    subcategory_title: "Administração",
    source_id: "anp",
    source_title: "ANP",
    slug: "aditamento-de-conteudo-local",
    title: "Aditamento de conteúdo local",
    description: "Aditamento de contratos de E&amp;P: Resolução ANP n° 726/2018 A Resolução ANP n° 726/2018 permitiu que as empresas que atuam em exploração e produção de petróleo e gás natural optassem por aditar a Cláusula de Conteúdo Local dos contratos vigentes, com efeitos para as fases não encerradas, conforme autorizado pela Resolução CNPE nº 1/2018, que permitiu a adoção de exigências de conteúdo local distintas daquelas vigentes nos contratos já celebrados. No total, foram atualizados os compromissos de conteúdo local para 266 contratos, alcançando 258 blocos exploratórios e eventuais campos decorrentes, além de 85 campos de produção. A relação completa dos contratos submetidos para aditamento e os dados finais de alcance dos Termos celebrados podem ser visualizados nesta página. O prazo para as em",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/aditamento-de-conteudo-local",
  },
  {
    id: "anp_acervo_de_dados_tecnicos",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Petróleo e gás",
    source_id: "anp",
    source_title: "ANP",
    slug: "acervo-de-dados-tecnicos",
    title: "Acervo de Dados Técnicos",
    description: "acervo de dados técnicos da ANP, armazenados no BDEP (Banco de Dados de Exploração e Produção), inclui dados de poços, dados sísmicos, dados não sísmicos, levantamentos geoquímicos, estudos de interpretação de dados, além dos respectivos relatórios e arquivos complementares. Informações sobre os dados técnicos cadastrados no acervo podem ser obtidas por meio das tabelas que se seguem, conforme o tipo de dado. Essas informações também são disponibilizadas pelo sistema de mapas GeoANP. Os dados técnicos tornam-se públicos após o final do período de sigilo (confidencialidade), durante o qual têm restrições de acesso. Esse período varia de dois a dez anos, dependendo do tipo de dado. Desde 2019, têm sido publicadas no site da ANP as relações dos dados de poços e sísmicos que se tornaram públic",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/acervo-de-dados-tecnicos",
  },
  {
    id: "anp_vendas_de_derivados_de_petroleo_e_biocombustiveis",
    category_title: "Mercado de commodities",
    segment_title: "Energia",
    subcategory_title: "Biocombustíveis e renováveis",
    source_id: "anp",
    source_title: "ANP",
    slug: "vendas-de-derivados-de-petroleo-e-biocombustiveis",
    title: "Vendas de derivados de petróleo e biocombustíveis",
    description: "As informações disponíveis são vendas de derivados de petróleo e etanol; vendas de combustíveis por segmento; vendas de combustíveis por tipo; vendas anuais de etanol hidratado e derivados de petróleo por município; e vendas anuais de etanol hidratado e derivados de petróleo por estado. Os dados são atualizados mensalmente até o último dia do mês subsequente ao mês de referência.",
    manifest_path: ANP_CATALOG_DATASET_PATH,
    source_url: "https://dados.gov.br/dados/conjuntos-dados/vendas-de-derivados-de-petroleo-e-biocombustiveis",
  },
];

